In [1]:
import numpy as np
from sklearn import datasets

np.random.seed(42)

### Dataset preparation

In [2]:
iris = datasets.load_iris()

x = iris.data
y = iris.target

class_names = iris.target_names
discribtion = iris.DESCR

In [3]:
print(f"class_names:\n{class_names}")
print(f"discription:\n{discribtion}")

class_names:
['setosa' 'versicolor' 'virginica']
discription:
.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  

In [4]:
print(f"x_shape:\n{x.shape}")
print(f"y_shape:\n{y.shape}")

print(f"x:\n{x}")
print(f"y:\n{y}")

x_shape:
(150, 4)
y_shape:
(150,)
x:
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7

### Dataset split

In [5]:
num_samples = x.shape[0]
num_features = x.shape[1]
num_classes = y.shape[0]

print(f"num_samples: {num_samples}")
print(f"num_features: {num_features}")
print(f"num_classes: {num_classes}")

num_samples: 150
num_features: 4
num_classes: 150


In [6]:
test_size = num_samples // 3

random_idxs = np.random.permutation(num_samples) # [0, num_samples-1b]

x_train = x[random_idxs[:-test_size]]
y_train = y[random_idxs[:-test_size]]

x_test = x[random_idxs[-test_size:]]
y_test = y[random_idxs[-test_size:]]

In [7]:
print(f"x_train_shape:\n{x_train.shape}")
print(f"y_train_shape:\n{y_train.shape}")

print(f"x_test_shape:\n{x_test.shape}")
print(f"y_test_shape:\n{y_test.shape}")

x_train_shape:
(100, 4)
y_train_shape:
(100,)
x_test_shape:
(50, 4)
y_test_shape:
(50,)


### KNN Model

In [8]:
from sklearn.neighbors import KNeighborsClassifier

clf = KNeighborsClassifier(n_neighbors=3)
clf.fit(x_train, y_train)

accuracy = clf.score(x_test, y_test)
print(f"accuracy: {accuracy*100.0:.4}%")

y_pred = clf.predict(x_test)
print(f"y_pred:\n{y_pred}")

accuracy: 96.0%
y_pred:
[0 0 0 2 2 0 2 2 0 1 1 2 1 2 0 2 1 2 1 1 1 0 1 1 0 1 2 2 0 1 2 2 0 2 0 1 2
 2 1 2 1 1 2 2 0 1 1 0 1 2]


### Try different hyperparameters

In [9]:
n_neighbors = [n_neighbor for n_neighbor in range(1,11)] # [1, 2, 3, ... 10]
weight_modes = ['uniform', 'distance']

# 10 x 2 = 20 Modelle
for n_neighbor in n_neighbors:
    for weight_mode in weight_modes:
        clf = KNeighborsClassifier(n_neighbors=n_neighbor, weights=weight_mode)
        clf.fit(x_train, y_train)
        accuracy = clf.score(x_test, y_test)
        print(f"Neighbors:  {n_neighbor}  Weight: {weight_mode}  Score: {accuracy:.4}")

Neighbors:  1  Weight: uniform  Score: 0.96
Neighbors:  1  Weight: distance  Score: 0.96
Neighbors:  2  Weight: uniform  Score: 0.96
Neighbors:  2  Weight: distance  Score: 0.96
Neighbors:  3  Weight: uniform  Score: 0.96
Neighbors:  3  Weight: distance  Score: 0.96
Neighbors:  4  Weight: uniform  Score: 0.96
Neighbors:  4  Weight: distance  Score: 0.96
Neighbors:  5  Weight: uniform  Score: 0.96
Neighbors:  5  Weight: distance  Score: 0.96
Neighbors:  6  Weight: uniform  Score: 0.96
Neighbors:  6  Weight: distance  Score: 0.96
Neighbors:  7  Weight: uniform  Score: 0.96
Neighbors:  7  Weight: distance  Score: 0.96
Neighbors:  8  Weight: uniform  Score: 0.98
Neighbors:  8  Weight: distance  Score: 0.96
Neighbors:  9  Weight: uniform  Score: 0.96
Neighbors:  9  Weight: distance  Score: 0.96
Neighbors:  10  Weight: uniform  Score: 0.96
Neighbors:  10  Weight: distance  Score: 0.96


### Best KNN Model

In [10]:
clf = KNeighborsClassifier(n_neighbors=8, weights='uniform')
clf.fit(x_train, y_train)

accuracy = clf.score(x_test, y_test)
print(f"accuracy: {accuracy*100.0:.4}%")

y_pred = clf.predict(x_test)
print(f"y_pred:\n{y_pred}")

y_pred_proba = clf.predict_proba(x_test)
print(f"y_pred_proba:\n{y_pred_proba}")

accuracy: 98.0%
y_pred:
[0 0 0 1 2 0 2 2 0 1 1 2 1 2 0 2 1 2 1 1 1 0 1 1 0 1 2 2 0 1 2 2 0 2 0 1 2
 2 1 2 1 1 2 2 0 1 1 0 1 2]
y_pred_proba:
[[1.    0.    0.   ]
 [1.    0.    0.   ]
 [1.    0.    0.   ]
 [0.    0.5   0.5  ]
 [0.    0.    1.   ]
 [1.    0.    0.   ]
 [0.    0.    1.   ]
 [0.    0.    1.   ]
 [1.    0.    0.   ]
 [0.    0.625 0.375]
 [0.    0.875 0.125]
 [0.    0.375 0.625]
 [0.    0.875 0.125]
 [0.    0.    1.   ]
 [1.    0.    0.   ]
 [0.    0.125 0.875]
 [0.    1.    0.   ]
 [0.    0.125 0.875]
 [0.    1.    0.   ]
 [0.    1.    0.   ]
 [0.    0.875 0.125]
 [1.    0.    0.   ]
 [0.    1.    0.   ]
 [0.    1.    0.   ]
 [1.    0.    0.   ]
 [0.    1.    0.   ]
 [0.    0.    1.   ]
 [0.    0.    1.   ]
 [1.    0.    0.   ]
 [0.    1.    0.   ]
 [0.    0.    1.   ]
 [0.    0.125 0.875]
 [1.    0.    0.   ]
 [0.    0.    1.   ]
 [1.    0.    0.   ]
 [0.    0.875 0.125]
 [0.    0.    1.   ]
 [0.    0.    1.   ]
 [0.    1.    0.   ]
 [0.    0.125 0.875]
 [0.    0.875 0.125